[browser]
showSidebarNavigation = false

[theme]

# Primary accent color.
primaryColor = "#EFEFD0" 

# Background color of the app.
backgroundColor = "#1A659E"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#004E89"

# Color used for almost all text.
textColor = "#F6F8FF"

headingFont = "serif"